language: php
dist: trusty

php:
  - 7.1

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer install --prefer-dist
  - nvm install node
  - npm install -g yarn
  - yarn --frozen-lockfile
  - yarn production

script:
 - ./vendor/bin/phpunit
